### ISSUE TITLE
django-rest-framework changelog

### ISSUE THREAD

**Issue by nikolas** [pyupio/changelogs#192] opened 2019-12-17 16:35 UTC
release notes for the 3.11.0 release are here: https://www.django-rest-framework.org/community/3.11-announcement/

**Comment by orsinium** [comment] 2020-01-22 15:43
I guess it's duplicate of #179

**Comment by orsinium** [comment] 2020-01-22 15:46
Let's dive deeper:

Duplicate of #159

**Comment by harlekeyn** [comment] 2020-10-11 21:37
Thanks, added!

**Closed by harlekeyn** 2020-10-11 21:37 UTC
