### ISSUE TITLE
Issues with coverage.py changelog

### ISSUE THREAD

**Issue by The-Compiler** [pyupio/changelogs#47] opened 2017-05-09 04:21 UTC
- https://pyup.io/changelogs/coverage/ only has 4.4b1 available, while the comment at https://github.com/qutebrowser/qutebrowser/pull/2609 has the 4.4 release too
- Looks like `<` and `>` are escaped inside code blocks while they shouldn't be, leading to `&lt;source&gt;`

**Comment by jayfk** [comment] 2017-05-19 08:19
> Looks like < and > are escaped inside code blocks while they shouldn't be, leading to &lt;source&gt;

This is interesting. I'd guess this was done by GitHub, but I'm unable to reproduce it. The bot isn't escaping anything, it just strips out issue cross links.

> https://pyup.io/changelogs/coverage/ only has 4.4b1 available, while the comment at qutebrowser/qutebrowser#2609 has the 4.4 release too

Probably a caching issue.

I'm closing this for now as there's nothing I can do to reproduce and fix this in retrospect, but thanks for raising this issue.

**Closed by jayfk** 2017-05-19 08:19 UTC
