### ISSUE TITLE
django-registration changelog location

### ISSUE THREAD

**Issue by nikolas** [pyupio/changelogs#83] opened 2017-12-05 20:30 UTC
https://github.com/macropin/django-registration/blob/master/CHANGELOG

**Comment by jayfk** [comment] 2018-02-05 15:14
Is this the correct changelog? It still says django-registration**-redux** .

**Comment by orsinium** [comment] 2020-01-22 15:53
Duplicate of #73

**Comment by harlekeyn** [comment] 2020-10-12 21:34
It's somewhat usable, and seemingly the best available. Thanks.

**Closed by harlekeyn** 2020-10-12 21:34 UTC
