### ISSUE TITLE
pytest changelog

### ISSUE THREAD

**Issue by lafrech** [pyupio/changelogs#102] opened 2018-03-23 07:29 UTC
> This PR updates pytest from 3.4.2 to 3.5.0.
> 
> The bot wasn't able to find a changelog for this release. Got an idea?

There you go: https://docs.pytest.org/en/latest/changelog.html

**Comment by edmorley** [comment] 2018-03-23 15:00
Also:
https://github.com/pytest-dev/pytest/blob/master/CHANGELOG.rst

**Comment by ntravis** [comment] 2018-04-02 20:54
dupe of #68

**Comment by jayfk** [comment] 2018-04-03 07:56
pytest should be working, just confirmed it via the CLI. Is it somehow possible that the changelog wasn't merged into master at the time of the release? 😕 

Investigating..

**Comment by jayfk** [comment] 2018-04-03 08:09
> dupe of #68

👍

**Closed by jayfk** 2018-04-03 08:09 UTC
